version: '3.9'
services:
  ubuntu-20-04:
    image: ubuntu:20.04
    restart: always
    working_dir: /workdir
    command: sleep 10d
    volumes:
      - ./:/workdir
      - ./custom-repo.list:/etc/apt/sources.list.d/custom-repo.list
  
  repository:
    image: nginx:1.25
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx/packages:/var/packages:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
